services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: random-assign-lambda
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-ap-northeast-1}
    env_file:
      - .env
    entrypoint: [] # override the entrypoint to empty array to prevent the default entrypoint of the lambda image
