service: random-assign-api

provider:
  name: aws
  runtime: python3.12
  region: ap-northeast-1
  memorySize: 128
  timeout: 10
  architecture: x86_64
  
functions:
  randomAssign:
    handler: handler.lambda_handler
    url: true
    events:
      - httpApi:
          path: /
          method: any

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3003
    host: 0.0.0.0

